jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: production  # Define an environment variable
    steps:
      - name: Print Environment
        run: echo "Deploying to $ENVIRONMENT"
