name: Manual Trigger Pipeline

on:
  workflow_dispatch:  # Allows manual trigger
    inputs:
      environment:
        description: "Select Deployment Environment"
        required: true
        default: "staging"
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Selected Environment
        run: echo "Deploying to ${{ inputs.environment }}"

      - name: Deploy to Development
        if: inputs.environment == 'development'
        run: echo "Running Development Deployment"

      - name: Deploy to Staging
        if: inputs.environment == 'staging'
        run: echo "Running Staging Deployment"

      - name: Deploy to Production
        if: inputs.environment == 'production'
        run: echo "Running Production Deployment"
